[project]
name = "enron-search"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.4",
    "rank-bm25>=0.2.2",
    "tiktoken>=0.9.0",
]
